#!/usr/bin/env php
<?php
require_once __DIR__.'/vendor/autoload.php';

use function Differ\Differ\gendiff;

// gendiff('/files/file1.json', '/files/file2.json');

$doc = <<<DOC
Generate diff

Usage:
  gendiff (-h|--help)
  gendiff (-v|--version)
  gendiff [--format <fmt>] <firstFile> <secondFile>

Options:
  -h --help                     Show this screen.
  --version                     Show version.
  --format <fmt>                Report format [default: stylish]

DOC;

$args = Docopt::handle($doc, array('version'=>'Gendiff 1.0'));
var_dump($args);
die();
foreach ($args as $k=>$v)
echo $v.PHP_EOL;
    //echo $k.': '.json_encode($v).PHP_EOL;